# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Dict, List, Optional
from aiohttp import ClientResponse
from pydantic import BaseModel, field_validator
from inference_perf.apis import InferenceAPIData, InferenceInfo, UnaryInferenceResponseInfo, StreamedInferenceResponseInfo
from inference_perf.utils.custom_tokenizer import CustomTokenizer
from inference_perf.config import APIConfig, APIType
from inference_perf.apis.streaming_parser import parse_sse_stream


# Fields allowed by the OpenAI/vLLM JSON Schema validator for tool parameters.
# Extra fields generated by Pydantic (e.g. 'default', 'title') are stripped.
_ALLOWED_JSON_SCHEMA_KEYS = {
    "type",
    "description",
    "enum",
    "properties",
    "required",
    "items",
    "anyOf",
    "oneOf",
    "allOf",
    "$ref",
    "const",
    "additionalProperties",
    "minimum",
    "maximum",
}


def _clean_schema(obj: Any, is_properties_map: bool = False) -> Any:
    """Recursively remove non-standard JSON Schema keys from a parameters dict.

    is_properties_map: when True, obj is the value of a 'properties' key —
    its keys are property names (not schema keywords) and must be preserved.

    vLLM requires every property schema to have a top-level 'type'. When a
    property uses only 'anyOf' (no 'type'), we inject 'type': 'string' as a
    safe fallback so the validator does not reject the tool definition.
    """
    if isinstance(obj, dict):
        if is_properties_map:
            return {k: _clean_schema(v) for k, v in obj.items()}
        cleaned = {}
        for k, v in obj.items():
            if k not in _ALLOWED_JSON_SCHEMA_KEYS:
                continue
            cleaned[k] = _clean_schema(v, is_properties_map=(k == "properties"))
        # vLLM requires a plain 'type' on every property schema and does not
        # support anyOf/oneOf. Collapse to 'type': 'string' as a safe fallback.
        if "type" not in cleaned:
            cleaned.pop("anyOf", None)
            cleaned.pop("oneOf", None)
            cleaned["type"] = "string"
        elif "anyOf" in cleaned or "oneOf" in cleaned:
            cleaned.pop("anyOf", None)
            cleaned.pop("oneOf", None)
        return cleaned
    if isinstance(obj, list):
        return [_clean_schema(v) for v in obj]
    return obj


def _clean_parameters(obj: Any) -> Any:
    return _clean_schema(obj)


class ChatMessage(BaseModel):
    role: str
    content: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None

    @field_validator("tool_calls")
    @classmethod
    def validate_tool_calls(cls, v: Optional[List[Dict[str, Any]]]) -> Optional[List[Dict[str, Any]]]:
        if v is None:
            return v
        for i, tc in enumerate(v):
            missing = {"id", "type", "function"} - tc.keys()
            if missing:
                raise ValueError(f"tool_calls[{i}] missing required keys: {missing}")
        return v

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to an OpenAI-compatible message dict."""
        msg: Dict[str, Any] = {"role": self.role}
        if self.tool_calls is not None:
            msg["tool_calls"] = self.tool_calls
            if self.content is not None:
                msg["content"] = self.content
        else:
            msg["content"] = self.content if self.content is not None else ""
        return msg


class ChatCompletionAPIData(InferenceAPIData):
    messages: List[ChatMessage]
    max_tokens: int = 0
    tool_definitions: Optional[List[Dict[str, Any]]] = None

    def get_api_type(self) -> APIType:
        return APIType.Chat

    def get_route(self) -> str:
        return "/v1/chat/completions"

    async def to_payload(
        self, effective_model_name: str, max_tokens: int, ignore_eos: bool, streaming: bool
    ) -> dict[str, Any]:
        if self.max_tokens == 0:
            self.max_tokens = max_tokens
        payload: Dict[str, Any] = {
            "model": effective_model_name,
            "messages": [m.to_dict() for m in self.messages],
            "max_tokens": self.max_tokens,
            "ignore_eos": ignore_eos,
            "stream": streaming,
            **({"stream_options": {"include_usage": True}} if streaming else {}),
        }
        if self.tool_definitions:
            tools = []
            for t in self.tool_definitions:
                if "function" in t:
                    # Already in OpenAI nested format: {"type": "function", "function": {...}}
                    # Still clean parameters so anyOf/oneOf schemas are normalised.
                    fn = t["function"]
                    tools.append(
                        {
                            "type": t.get("type", "function"),
                            "function": {
                                "name": fn["name"],
                                "description": fn.get("description"),
                                "parameters": _clean_parameters(fn.get("parameters")),
                            },
                        }
                    )
                else:
                    # Flat format: {"type": "function", "name": ..., "description": ..., "parameters": ...}
                    tools.append(
                        {
                            "type": t["type"],
                            "function": {
                                "name": t["name"],
                                "description": t.get("description"),
                                "parameters": _clean_parameters(t.get("parameters")),
                            },
                        }
                    )
            payload["tools"] = tools
        return payload

    async def process_response(
        self, response: ClientResponse, config: APIConfig, tokenizer: CustomTokenizer, lora_adapter: Optional[str] = None
    ) -> InferenceInfo:
        if config.streaming:
            # Use shared streaming parser with chat-specific content extraction
            output_text, chunk_times, raw_content, response_chunks, server_usage = await parse_sse_stream(
                response, extract_content=lambda data: data.get("choices", [{}])[0].get("delta", {}).get("content")
            )

            prompt_text = "".join([msg.content for msg in self.messages if msg.content is not None])
            prompt_len = tokenizer.count_tokens(prompt_text)
            output_len = tokenizer.count_tokens(output_text)
            return InferenceInfo(
                input_tokens=prompt_len,
                response_info=StreamedInferenceResponseInfo(
                    response_chunks=response_chunks,
                    chunk_times=chunk_times,
                    output_tokens=output_len,
                    output_token_times=chunk_times,
                    server_usage=server_usage,
                ),
                lora_adapter=lora_adapter,
                extra_info={"raw_response": raw_content},
            )
        else:
            data = await response.json()
            prompt_len = tokenizer.count_tokens("".join([m.content for m in self.messages if m.content is not None]))
            choices = data.get("choices", [])
            if len(choices) == 0:
                return InferenceInfo(input_tokens=prompt_len, lora_adapter=lora_adapter)
            output_text = "".join([choice.get("message", {}).get("content", "") for choice in choices])
            output_len = tokenizer.count_tokens(output_text)
            return InferenceInfo(
                input_tokens=prompt_len,
                response_info=UnaryInferenceResponseInfo(output_tokens=output_len),
                lora_adapter=lora_adapter,
            )
