# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `NodeOutputRegistry`, which maps
node_id → actual output text. The registry is backed by a `multiprocessing.Manager().dict()`
so it is shared across all worker processes.

The actual output is captured in `OTelChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.
"""

import json
import logging
import multiprocessing as mp
import random
import time
from dataclasses import dataclass, field, replace as dc_replace
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import Any, Callable, Dict, Generator, List, Optional, Set

from aiohttp import ClientResponse

from inference_perf.apis import ChatCompletionAPIData, InferenceAPIData, InferenceInfo, LazyLoadInferenceAPIData, SessionLifecycleMetric, ErrorResponseInfo
from inference_perf.apis.chat import ChatMessage
from inference_perf.config import APIConfig, APIType, DataConfig
from inference_perf.datagen.base import DataGenerator, LazyLoadDataMixin
from inference_perf.datagen.otel_trace_to_replay_graph import (
    GraphCall,
    GraphNode,
    InputSegment,
    ReplayGraph,
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SessionGraphState — tracks graph traversal state for one session
# ---------------------------------------------------------------------------

@dataclass
class SessionGraphState:
    """Tracks graph traversal state for one session.

    Manages which nodes are ready to dispatch, which have been dispatched,
    and which have completed. Used for graph-based traversal.
    """
    session_id: str
    graph: ReplayGraph
    ready_nodes: Set[str]  # node_ids ready to dispatch (predecessors done)
    dispatched_nodes: Set[str]  # node_ids already dispatched
    completed_nodes: Set[str]  # node_ids that have completed
    node_completion_times: Dict[str, float]  # node_id → completion timestamp
    is_active: bool = False  # Is this session currently active?
    is_complete: bool = False  # Has this session finished all nodes?


# ---------------------------------------------------------------------------
# OTelInferenceInfo — InferenceInfo subclass that carries the output text
# ---------------------------------------------------------------------------

class OTelInferenceInfo(InferenceInfo):
    """InferenceInfo subclass that also carries the raw output text.

    Inherits all fields from InferenceInfo (input_tokens, output_tokens, etc.)
    and adds output_text so the OTel replay path can register the actual
    generated text in the NodeOutputRegistry without touching the base class.
    """
    output_text: Optional[str] = None


# ---------------------------------------------------------------------------
# NodeOutputRegistry — shared cross-process output store
# ---------------------------------------------------------------------------

class NodeOutputRegistry:
    """Thread- and process-safe registry mapping node_id → actual output text.

    Backed by a multiprocessing.Manager().dict() so all worker processes share
    the same store. The manager must be started before the workers are forked.

    Usage:
        manager = mp.Manager()
        registry = NodeOutputRegistry(manager)
        # pass registry to OTelTraceReplayDataGenerator
        # workers call registry.record(node_id, text) after each LLM call
        # load_lazy_data calls registry.require(node_id) to get the output
    """

    def __init__(self, manager: Optional[SyncManager] = None) -> None:
        if manager is not None:
            # Shared across processes via manager proxy
            self._node_output_text: Dict[str, str] = manager.dict()  # type: ignore[assignment]
            self._node_input_messages: Dict[str, Any] = manager.dict()  # type: ignore[assignment]
        else:
            # Single-process fallback (e.g., tests, num_workers=0)
            self._node_output_text = {}
            self._node_input_messages = {}

    def record(self, node_id: str, output_text: str, messages=None) -> None:
        """Register the actual output text for a completed node.

        Args:
            node_id: The node ID
            output_text: The actual generated output
            messages: The input messages
        """
        self._node_output_text[node_id] = output_text
        if messages:
            self._node_input_messages[node_id] = list(messages)  # Convert to list for storage

    def get(self, node_id: str) -> Optional[str]:
        """Return the output text for node_id, or None if not yet registered."""
        return self._node_output_text.get(node_id)

    def get_output_by_node_id(self, node_id: str) -> Optional[str]:
        """Return the output text for a given node_id."""
        return self._node_output_text.get(node_id)
    
    def get_messages_by_node_id(self, node_id: str) -> Optional[List[Any]]:
        """Return the input messages for a given node_id.
        
        Args:
            node_id: The node ID to look up
            
        Returns:
            List of input messages, or None if not found
        """
        return self._node_input_messages.get(node_id)
    
    def get_node_ids(self) -> List[str]:
        """Return all registered node IDs.
        
        Returns:
            List of all node IDs that have registered outputs
        """
        return list(self._node_output_text.keys())

    def require(self, node_id: str, timeout_sec: float = 30.0) -> str:
        """Return the output text for node_id, waiting if not yet registered.

        This is called when building the messages for a call that has an "output"
        segment sourced from node_id. If the predecessor has not yet completed,
        this method polls the registry until the output becomes available or timeout.

        Args:
            node_id: The node ID whose output is required
            timeout_sec: Maximum time to wait for the output (default: 30s)

        Returns:
            The output text from the predecessor node

        Raises:
            TimeoutError: If the output is not available within timeout_sec
        """
        start_time = time.time()
        poll_interval = 0.01  # 10ms initial poll interval
        max_poll_interval = 0.5  # Max 500ms between polls
        last_log_time = start_time

        while True:
            output = self._node_output_text.get(node_id)
            if output is not None:
                elapsed = time.time() - start_time
                if elapsed > 0.1:  # Log if we had to wait
                    logger.debug(f"Got output for node {node_id} after {elapsed:.2f}s wait")
                return output

            elapsed = time.time() - start_time
            
            # Log every 2 minute while waiting
            if elapsed - (last_log_time - start_time) >= 120.0:
                logger.warning(
                    f"Still waiting for output from node '{node_id}' ({elapsed:.1f}s elapsed)"
                )
                last_log_time = time.time()
            
            if elapsed >= timeout_sec:
                raise TimeoutError(
                    f"NodeOutputRegistry: output for node '{node_id}' not available after "
                    f"{timeout_sec:.1f}s. This means the predecessor call has not completed "
                    f"within the timeout period. Check that predecessor_node_ids are correct "
                    f"and that the predecessor is not blocked or failed."
                )

            # Exponential backoff for polling
            time.sleep(min(poll_interval, max_poll_interval))
            poll_interval *= 1.5

    def wait_for_all(self, node_ids: List[str], timeout_sec: float = 30.0) -> None:
        """Wait for all specified nodes to have registered outputs.

        Args:
            node_ids: List of node IDs to wait for
            timeout_sec: Maximum time to wait for all outputs (default: 30s)

        Raises:
            TimeoutError: If any output is not available within timeout_sec
        """
        if not node_ids:
            return
        
        logger.debug(f"Waiting for {len(node_ids)} predecessor(s): {node_ids}")
        for node_id in node_ids:
            self.require(node_id, timeout_sec=timeout_sec)
        logger.debug(f"All {len(node_ids)} predecessor(s) completed")


# ---------------------------------------------------------------------------
# OTelChatCompletionAPIData — captures output and registers it in the registry
# ---------------------------------------------------------------------------

class OTelChatCompletionAPIData(ChatCompletionAPIData):
    """ChatCompletionAPIData subclass for OTel trace replay.

    Overrides process_response to:
    1. Extract the actual output text from the LLM response.
    2. Register it in the NodeOutputRegistry under this call's node_id.
    3. Return OTelInferenceInfo (InferenceInfo subclass) with output_text populated.

    The registry and node_id are passed at construction time via Pydantic fields.
    arbitrary_types_allowed is required because NodeOutputRegistry is not a Pydantic model.
    
    Dependency handling:
    - predecessor_node_ids: List of nodes that must complete before this one
    - wait_ms: Additional delay after predecessors complete
    - input_segments: Segment decomposition for output substitution
    - original_messages: Original messages before substitution (used as template)
    """

    model_config = {"arbitrary_types_allowed": True}

    node_id: str
    registry: NodeOutputRegistry
    
    # Dependency information for async waiting
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0
    input_segments: List[InputSegment] = field(default_factory=list)
    original_messages: List[Dict[str, Any]] = field(default_factory=list)
    expected_output_content: Optional[str] = None
    
    # Completion callback for graph traversal
    completion_callback: Optional[Callable[[str, float], None]] = None
    
    async def wait_for_predecessors_and_substitute(self) -> None:
        """Wait for predecessors asynchronously and substitute output segments.
        
        This method is called by the worker before dispatching the HTTP request.
        It ensures that all predecessor nodes have completed and their outputs
        are available, then substitutes "output" segments with actual predecessor
        outputs instead of the recorded assistant messages.
        
        The waiting is done in an executor to avoid blocking the event loop.
        """
        import asyncio
        
        if self.predecessor_node_ids:
            logger.debug(
                f"Node {self.node_id} waiting for {len(self.predecessor_node_ids)} predecessor(s): "
                f"{self.predecessor_node_ids}"
            )
            # Run blocking wait in executor to avoid blocking event loop
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                self.registry.wait_for_all,
                self.predecessor_node_ids,
                3600.0  # 1 hour timeout
            )
            logger.debug(f"Node {self.node_id} predecessors completed")
        
        # Wait additional delay specified in wait_ms
        if self.wait_ms > 0:
            wait_sec = self.wait_ms / 1000.0
            logger.debug(f"Node {self.node_id} waiting {wait_sec:.3f}s (wait_ms={self.wait_ms})")
            await asyncio.sleep(wait_sec)
        
        # Substitute output segments with actual predecessor outputs and also the shared segments after substitution
        if any(seg.type == "output" or seg.type == "shared" for seg in self.input_segments):
            logger.debug(f"Node {self.node_id} substituting output/shared segments")
            substituted = self._build_messages_with_substitution()
            # Update messages with substituted content
            self.messages = [
                ChatMessage(role=m["role"], content=m["content"])
                for m in substituted
            ]
            logger.debug(f"Node {self.node_id} substitution complete, {len(self.messages)} messages")

    def _build_messages_with_substitution(self) -> List[Dict[str, Any]]:
        """Build messages with output segments substituted with actual predecessor outputs.

        For assistant messages, we substitute their output messages with the actual output.
        """
        if not self.input_segments:
            return self.original_messages

        result = []
        cursor = 0

        for seg in self.input_segments:
            seg_msgs = self.original_messages[cursor:cursor + seg.message_count]

            if seg.type == "output":
                # Output segment: substitute with actual output from the specific predecessor
                if seg.source_node_id:
                    actual_output = self.registry.get_output_by_node_id(seg.source_node_id)
                    logger.debug(
                        f"Registry get for node {self.node_id} output segment from {seg.source_node_id} generated: {actual_output}")

                    if actual_output:
                        for msg in seg_msgs:
                            substituted = dict(msg)
                            substituted["content"] = actual_output
                            result.append(substituted)
                        logger.debug(
                            f"Node {self.node_id}: substituted output segment "
                            f"with actual output from {seg.source_node_id}"
                        )
                    else:
                        logger.warning(
                            f"Node {self.node_id}: output segment from {seg.source_node_id} "
                            f"not available, using recorded content"
                        )
                        result.extend(seg_msgs)
                else:
                    logger.warning(
                        f"Node {self.node_id}: output segment has no source_node_id, "
                        f"using recorded content"
                    )
                    result.extend(seg_msgs)
            elif seg.type == "shared":
                seg_msgs_from_parent = self.registry.get_messages_by_node_id(seg.source_node_id)
                logger.debug(f"Registry get for node {self.node_id} from {seg.source_node_id} shared segment from {seg.source_node_id} num messages in parent node: {len(seg_msgs_from_parent)}")
                if len(seg_msgs_from_parent) != len(seg_msgs):
                    logger.error(f"***************** node {self.node_id} shared segment from {seg.source_node_id} had different number of messages in parent node: {len(seg_msgs_from_parent)}, num messages in seg: {len(seg_msgs)}")
                for msg_idx, msg in enumerate(seg_msgs_from_parent):
                    result.append(dict(msg))
            elif seg.type == "unique":
                # Unique message, keep as-is
                for msg_idx, msg in enumerate(seg_msgs):
                    result.append(msg)
            else:
                # Unknown segment type, keep as-is
                result.extend(seg_msgs)

            cursor += seg.message_count

        return result

    
    def on_completion(self, info: InferenceInfo) -> None:
        """Called after every request completes (real or mock) to register output and unblock successors."""
        output_text = info.output_text if isinstance(info, OTelInferenceInfo) else ""
        output_text = output_text or ""
        self.registry.record(self.node_id, output_text, self.messages)
        logger.debug(f"calling registry record for node {self.node_id} num input messages {len(self.messages)} and output: {output_text}")
        if self.completion_callback:
            logger.debug(f"Calling completion callback for node {self.node_id}")
            self.completion_callback(self.node_id, time.perf_counter())
            logger.debug(f"Completion callback finished for node {self.node_id}")
        else:
            logger.warning(f"No completion callback set for node {self.node_id}")


    async def process_response(
        self,
        response: ClientResponse,
        config: APIConfig,
        tokenizer: CustomTokenizer,
        lora_adapter: Optional[str] = None,
    ) -> OTelInferenceInfo:
        """Process the LLM response, capture output text, and register it."""
        logger.debug(f"process_response called for node {self.node_id}")
        output_text: str = ""

        if config.streaming:
            output_text = ""
            output_token_times: List[float] = []
            buffer = b""
            async for chunk in response.content.iter_any():
                buffer += chunk
                while b"\n\n" in buffer:
                    message, buffer = buffer.split(b"\n\n", 1)
                    output_token_times.append(time.perf_counter())
                    for line in message.split(sep=b"\n"):
                        if line.startswith(b"data:"):
                            data_str = line.removeprefix(b"data: ").strip()
                            if data_str == b"[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                choices = data.get("choices", [])
                                if choices:
                                    delta = choices[0].get("delta", {})
                                    content = delta.get("content")
                                    if content:
                                        output_text += content
                            except (json.JSONDecodeError, IndexError):
                                continue
                    else:
                        continue
                    break

            prompt_text = "".join([msg.content for msg in self.messages if msg.content])
            prompt_len = tokenizer.count_tokens(prompt_text)
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                output_token_times=output_token_times,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )
        else:
            data = await response.json()
            prompt_len = tokenizer.count_tokens("".join([m.content for m in self.messages]))
            choices = data.get("choices", [])
            if choices:
                output_text = "".join(
                    [choice.get("message", {}).get("content", "") for choice in choices]
                )
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )

        # Register output and notify successors.
        self.on_completion(info)

        if output_text:
            logger.debug(
                f"Registered output for node {self.node_id}: {len(output_text)} chars : {output_text}"
            )
        else:
            logger.debug(f"Registered empty output for node {self.node_id}")

        return info


# ---------------------------------------------------------------------------
# OTelTraceReplayEvent — one event per graph node
# ---------------------------------------------------------------------------

@dataclass
class OTelTraceReplayEvent:
    """Represents a single LLM request event from an OTel trace, derived from a GraphCall."""

    call_id: str
    node_id: str
    file_index: int
    t_start_ms: int   # node start time (adjusted for time_scale + session offset)
    t_end_ms: int     # node end time
    model: str
    messages: List[Dict[str, Any]]          # original (recorded) messages — used as template
    expected_output: str
    input_segments: List[InputSegment]      # segment decomposition for output substitution
    expected_output_tokens: int
    temperature: Optional[float]
    max_tokens_recorded: Optional[int]
    # Predecessor node IDs (nodes that must complete before this one starts)
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0


@dataclass
class OTelTraceSession:
    """Represents a complete session (one OTel file) as a ReplayGraph."""

    session_id: str
    file_path: Path
    file_index: int
    graph: ReplayGraph
    start_offset_ms: int = 0  # Offset for staggered session starts


class OTelTraceReplayDataGenerator(DataGenerator, LazyLoadDataMixin):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.
    
    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """
    
    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
    ) -> None:
        super().__init__(api_config, config, tokenizer)

        if not hasattr(config, 'otel_trace_replay') or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")

        self.otel_config = config.otel_trace_replay
        self.mp_manager = mp_manager
        self.base_seed = base_seed if base_seed is not None else 42
        
        # Determine loading mode: directory or list of files
        if self.otel_config.trace_directory:
            self.trace_dir: Optional[Path] = Path(self.otel_config.trace_directory)
            self.load_mode = "directory"
            
            if not self.trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {self.trace_dir}")
            
            if not self.trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {self.trace_dir}")
        elif self.otel_config.trace_files:
            # Multiple files mode
            self.trace_files_list = [Path(f) for f in self.otel_config.trace_files]
            self.load_mode = "files_list"
            self.trace_dir = None  # Not needed for files_list mode
            
            # Validate all files exist and are JSON
            for trace_file in self.trace_files_list:
                if not trace_file.exists():
                    raise ValueError(f"Trace file does not exist: {trace_file}")
                if not trace_file.is_file():
                    raise ValueError(f"Trace file path is not a file: {trace_file}")
                if trace_file.suffix != '.json':
                    raise ValueError(f"Trace file must be a JSON file: {trace_file}")
        else:
            raise ValueError("Either trace_directory or trace_files must be provided in otel_trace_replay config")

        # Output registry: shared across all worker processes via mp.Manager().dict()
        # If mp_manager is None (single-process mode), falls back to a plain dict.
        self.output_registry = NodeOutputRegistry(manager=mp_manager)

        # Shared session-node completion tracker for cross-process coordination
        # Maps qualified_node_id -> completion_time (shared via Manager)
        if mp_manager is not None:
            self._shared_node_completions: Dict[str, float] = mp_manager.dict()  # type: ignore[assignment]
        else:
            self._shared_node_completions = {}

        # Accumulated session-level metrics (populated by LoadGen at session completion)
        self._session_metrics: List[SessionLifecycleMetric] = []

        # Load and process all OTel trace files
        self.sessions: List[OTelTraceSession] = []
        self._load_trace_files()

        # Session state tracking (LoadGen controls which sessions are active)
        self.session_graph_state: Dict[str, SessionGraphState] = {}

        # Event index mappings
        self.event_to_session: Dict[int, str] = {}  # event_idx → session_id
        self.event_to_node: Dict[int, str] = {}  # event_idx → node_id

        if not self.sessions:
            raise ValueError(f"No valid OTel trace files found")

        # Build flat list of all events across all sessions for replay
        self._build_replay_schedule()

        logger.debug(
            f"Loaded {len(self.sessions)} sessions with {len(self.all_events)} total events"
        )
    
    def _load_trace_files(self) -> None:
        """Load and process OTel JSON files based on the configured mode."""
        if self.load_mode == "files_list":
            # Multiple files mode: load specific list of files
            logger.info(f"Loading {len(self.trace_files_list)} specified trace files")
            for file_index, trace_file in enumerate(self.trace_files_list):
                try:
                    session = self._process_trace_file(trace_file, file_index)
                    if session:
                        self.sessions.append(session)
                        node_count = len(session.graph.nodes)
                        logger.info(
                            f"Loaded session {session.session_id} from {trace_file.name} "
                            f"with {node_count} nodes"
                        )
                except Exception as e:
                    logger.error(f"Failed to process trace file {trace_file}: {e}")
                    if not self.otel_config.skip_invalid_files:
                        raise
        elif self.load_mode == "directory":
            # Directory mode: load all JSON files from the directory
            if self.trace_dir is None:
                raise ValueError("trace_dir must be set for directory mode")
            
            trace_files = sorted(self.trace_dir.glob("*.json"))
            
            if not trace_files:
                logger.warning(f"No JSON files found in {self.trace_dir}")
                return
            
            logger.info(f"Found {len(trace_files)} trace files in {self.trace_dir}")
            
            for file_index, trace_file in enumerate(trace_files):
                try:
                    session = self._process_trace_file(trace_file, file_index)
                    if session:
                        self.sessions.append(session)
                        node_count = len(session.graph.nodes)
                        logger.info(
                            f"Loaded session {session.session_id} from {trace_file.name} "
                            f"with {node_count} nodes"
                        )
                except Exception as e:
                    logger.error(f"Failed to process trace file {trace_file}: {e}")
                    if not self.otel_config.skip_invalid_files:
                        raise
        
        # Randomize session order using base_seed for reproducibility
        random.seed(self.base_seed)
        random.shuffle(self.sessions)
        logger.info(f"Randomized session order using seed: {self.base_seed}")
    
    def _process_trace_file(self, trace_file: Path, file_index: int) -> Optional[OTelTraceSession]:
        """Process a single OTel JSON trace file into a ReplayGraph session."""
        try:
            data = json.loads(trace_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {trace_file}: {e}")
            return None

        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {trace_file}")
            return None

        raw_calls = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
        if not raw_calls:
            logger.warning(f"No LLM calls found in {trace_file}")
            return None

        graph = build_graph(
            raw_calls,
            source_file=str(trace_file),
        )

        # Use trace_id from first call as session_id, but make it unique by adding file_index
        # to handle cases where multiple files have the same trace_id
        base_session_id = raw_calls[0].trace_id or f"session_{file_index}"
        session_id = f"file{file_index}_{base_session_id}"

        return OTelTraceSession(
            session_id=session_id,
            file_path=trace_file,
            file_index=file_index,
            graph=graph,
        )

    def _build_replay_schedule(self) -> None:
        """Build the replay schedule using graph traversal (no time-based sorting).
        
        Creates event list and initializes session graph states for traversal.
        Sessions are activated on-demand based on concurrent_sessions limit.
        """
        self.all_events: List[OTelTraceReplayEvent] = []
        
        for session in self.sessions:
            # Initialize session graph state
            state = SessionGraphState(
                session_id=session.session_id,
                graph=session.graph,
                ready_nodes=set(),  # Will be populated when session is activated
                dispatched_nodes=set(),
                completed_nodes=set(),
                node_completion_times={},
                is_active=False,
                is_complete=False,
            )
            self.session_graph_state[session.session_id] = state
            
            # Build events for indexing (no time-based sorting)
            for node in session.graph.nodes.values():
                gc = node.call
                
                if not gc.messages:
                    logger.warning(f"Call {gc.call_id} in node {node.node_id} has no messages, skipping")
                    continue
                
                # Qualify node_id with session to avoid collisions
                qualified_node_id = f"{session.session_id}:{node.node_id}"
                qualified_predecessor_ids = [
                    f"{session.session_id}:{pid}" for pid in node.predecessor_node_ids
                ]

                # Rewrite source_node_id in input_segments
                qualified_segments = [
                    dc_replace(seg, source_node_id=f"{session.session_id}:{seg.source_node_id}")
                    if seg.source_node_id is not None
                    else seg
                    for seg in gc.input_segments
                ]
                
                event_idx = len(self.all_events)
                
                self.all_events.append(OTelTraceReplayEvent(
                    call_id=gc.call_id,
                    node_id=qualified_node_id,
                    file_index=session.file_index,
                    t_start_ms=0,  # Not used in graph traversal
                    t_end_ms=0,    # Not used in graph traversal
                    model=gc.model,
                    messages=gc.messages,
                    expected_output=gc.expected_output,
                    input_segments=qualified_segments,
                    expected_output_tokens=gc.expected_output_tokens,
                    temperature=gc.temperature,
                    max_tokens_recorded=gc.max_tokens_recorded,
                    predecessor_node_ids=qualified_predecessor_ids,
                    wait_ms=node.wait_ms,
                ))
                
                # Build index mappings
                self.event_to_session[event_idx] = session.session_id
                self.event_to_node[event_idx] = node.node_id
        
        # NO SORTING - events accessed by index via mappings
        

        logger.info(
            f"Built replay schedule: {len(self.all_events)} events across "
            f"{len(self.sessions)} sessions (graph-based traversal)"
        )

    def _activate_session(self, session_id: str) -> None:
        """Activate a session by marking it active and enabling root nodes."""
        state = self.session_graph_state[session_id]
        state.is_active = True
        self.active_session_ids.add(session_id)
        
        # Find and activate root nodes (no predecessors)
        root_nodes = {
            node_id for node_id, node in state.graph.nodes.items()
            if not node.predecessor_node_ids
        }
        state.ready_nodes.update(root_nodes)
        
        logger.info(f"Activated session {session_id} with {len(root_nodes)} root nodes")
    
    def _get_effective_model(self, recorded_model: str) -> str:
        """Get the effective model name for a request."""
        if self.otel_config.use_static_model:
            # Use static model from config
            return self.otel_config.static_model_name
        else:
            # Use model mapping if provided
            if self.otel_config.model_mapping:
                return self.otel_config.model_mapping.get(recorded_model, recorded_model)
            return recorded_model

    def get_request_count(self) -> int:
        """Return total number of requests to replay from active sessions only.
        
        Only counts events from currently active sessions, not pending ones.
        Pending sessions will be activated later and their events yielded in subsequent calls.
        """
        # Count events from active sessions only
        total_events = 0
        
        for session_id in self.active_session_ids:
            state = self.session_graph_state.get(session_id)
            if state:
                total_events += len(state.graph.nodes)
        
        logger.info(
            f"get_request_count: {total_events} events from "
            f"{len(self.active_session_ids)} active session(s) "
            f"({len(self.pending_session_ids)} pending)"
        )
        
        return total_events
    
    def get_supported_apis(self) -> List[APIType]:
        """Return supported API types."""
        return [APIType.Chat]
    
    def is_io_distribution_supported(self) -> bool:
        """IO distribution not supported for trace replay."""
        return False
    
    def is_shared_prefix_supported(self) -> bool:
        """Shared prefix not supported for trace replay."""
        return False
    
    def get_session_count(self) -> int:
        """Return the total number of sessions (trace files) available for replay."""
        return len(self.sessions)
    
    def get_session_event_indices(self, session_index: int) -> List[int]:
        """Get the event indices for a specific session.
        
        Args:
            session_index: Index of the session (0-based)
            
        Returns:
            List of event indices (into self.all_events) that belong to this session
            
        Raises:
            IndexError: If session_index is out of range
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")
        
        session = self.sessions[session_index]
        # Find all events that belong to this session by matching file_index
        return [i for i, event in enumerate(self.all_events) if event.file_index == session.file_index]
    
    def get_session_info(self, session_index: int) -> Dict[str, Any]:
        """Get information about a specific session.
        
        Args:
            session_index: Index of the session (0-based)
            
        Returns:
            Dictionary with session metadata
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")
        
        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)
        
        return {
            "session_id": session.session_id,
            "file_path": str(session.file_path),
            "file_index": session.file_index,
            "num_events": len(event_indices),
            "num_nodes": len(session.graph.nodes),
            "start_offset_ms": session.start_offset_ms,
        }

    def get_session_events(self, session_index: int) -> List[LazyLoadInferenceAPIData]:
        """Get all events for a specific session as LazyLoadInferenceAPIData.

        This is used by LoadGen to dispatch a session's events.

        Args:
            session_index: Index of the session (0-based)

        Returns:
            List of LazyLoadInferenceAPIData for this session's events
        """
        event_indices = self.get_session_event_indices(session_index)
        return [LazyLoadInferenceAPIData(data_index=idx) for idx in event_indices]

    def record_session_metric(self, metric: SessionLifecycleMetric) -> None:
        """Record a completed session's lifecycle metric."""
        self._session_metrics.append(metric)

    def get_session_metrics(self) -> List[SessionLifecycleMetric]:
        """Return all recorded session lifecycle metrics."""
        return self._session_metrics

    def build_session_metric(
        self,
        session_id: str,
        stage_id: int,
        start_time: float,
        end_time: float,
    ) -> SessionLifecycleMetric:
        """Build a SessionLifecycleMetric for a completed session.

        Token totals are left at 0 here and filled in later by the report
        generator once all metrics have been collected (the multiprocess
        collector only exposes metrics after the full run completes).

        Args:
            session_id: The session ID
            stage_id: The stage this session ran in
            start_time: Wall-clock epoch when the session was dispatched
            end_time: Wall-clock epoch when the session completed
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            raise ValueError(f"Unknown session: {session_id}")

        # Find the file_path for this session
        file_path = ""
        for session in self.sessions:
            if session.session_id == session_id:
                file_path = str(session.file_path)
                break

        num_nodes = len(state.graph.nodes)
        num_nodes_completed = len(state.completed_nodes)

        return SessionLifecycleMetric(
            session_id=session_id,
            stage_id=stage_id,
            file_path=file_path,
            start_time=start_time,
            end_time=end_time,
            duration_sec=end_time - start_time,
            num_nodes=num_nodes,
            num_nodes_completed=num_nodes_completed,
        )

    def activate_session(self, session_id: str) -> None:
        """Internal method to activate a session (mark nodes as ready).

        This is called by LoadGen when it decides to start a session.
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to activate unknown session: {session_id}")
            return

        state.is_active = True

        # Find and activate root nodes (no predecessors)
        root_nodes = {
            node_id for node_id, node in state.graph.nodes.items()
            if not node.predecessor_node_ids
        }
        state.ready_nodes.update(root_nodes)

        logger.info(f"Activated session {session_id} with {len(root_nodes)} root nodes")

    def check_session_completed(self, session_id: str) -> bool:
        """Check if a specific session has completed all its nodes.

        Args:
            session_id: The session ID to check

        Returns:
            True if all nodes in the session have completed, False otherwise
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to check unknown session: {session_id}")
            return False

        # Check completion tracker for all nodes in this session
        for node_id in state.graph.nodes.keys():
            qualified_node_id = f"{session_id}:{node_id}"
            if qualified_node_id in self._shared_node_completions:
                # Record in local state if not already recorded
                if node_id not in state.completed_nodes:
                    completion_time = self._shared_node_completions[qualified_node_id]
                    state.completed_nodes.add(node_id)
                    state.node_completion_times[node_id] = completion_time

        # Session is complete if all nodes are complete
        is_complete = len(state.completed_nodes) == len(state.graph.nodes)

        if is_complete and not state.is_complete:
            state.is_complete = True
            logger.info(f"Session {session_id} completed all {len(state.graph.nodes)} nodes")

        return is_complete

    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        """Load the actual request data for a given index.

        This method NO LONGER blocks waiting for predecessors. Instead, it passes
        the dependency information (predecessor_node_ids, wait_ms, input_segments)
        to the OTelChatCompletionAPIData instance, which will handle async waiting
        in the worker before dispatching the HTTP request.

        This prevents deadlock: workers don't block synchronously, so they can
        process multiple requests and complete predecessors while others wait.

        Returns an OTelChatCompletionAPIData instance that will:
        1. Wait for predecessors asynchronously (in worker)
        2. Substitute output segments with actual predecessor outputs
        3. Register its own output after the LLM call completes
        """
        n = data.data_index

        if n >= len(self.all_events):
            raise IndexError(f"Event index {n} out of range (total: {len(self.all_events)})")

        event = self.all_events[n]

        # Convert messages to ChatMessage objects (no substitution yet - that happens async)
        chat_messages = []
        for msg in event.messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")

            # Handle content that might be a list (tool blocks)
            if isinstance(content, list):
                content_parts = []
                for block in content:
                    if isinstance(block, dict):
                        if block.get("type") == "text":
                            content_parts.append(block.get("text", ""))
                        else:
                            content_parts.append(json.dumps(block))
                    else:
                        content_parts.append(str(block))
                content = " ".join(content_parts)

            chat_messages.append(ChatMessage(role=role, content=str(content)))

        # Use expected_output_tokens (from trace) so downstream prefix matching works.
        # Fall back to config default if not available.
        max_tokens = event.expected_output_tokens or self.otel_config.default_max_tokens

        # Return OTelChatCompletionAPIData with dependency info
        # The worker will call wait_for_predecessors_and_substitute() before dispatching
        return OTelChatCompletionAPIData(
            messages=chat_messages,
            max_tokens=max_tokens,
            node_id=event.node_id,
            registry=self.output_registry,
            # Pass dependency info for async handling
            predecessor_node_ids=event.predecessor_node_ids,
            wait_ms=event.wait_ms,
            input_segments=event.input_segments,
            original_messages=event.messages,
            expected_output_content=event.expected_output, #expected_output_content,
            # Pass completion callback for graph traversal
            completion_callback=self._on_node_completed,
        )

    def get_data(self) -> Generator[InferenceAPIData, None, None]:
        """OTel trace replay only works with TRACE_SESSION_REPLAY load type.

        This method should never be called. If you see this error, check your config:
        - data.type must be 'otel_trace_replay'
        - load.type must be 'trace_session_replay'

        The config validation should have caught this at startup.
        """
        raise NotImplementedError(
            "OTel trace replay requires load.type='trace_session_replay'. "
            "Cannot use with CONSTANT, POISSON, or CONCURRENT load types. "
            "Use get_session_events() instead."
        )

    def _find_event_index(self, session_id: str, node_id: str) -> int:
        """Find the event index for a given session and node_id.
        
        Uses the event_to_session and event_to_node mappings for O(n) lookup.
        Could be optimized with a reverse index if needed.
        """
        qualified_node_id = f"{session_id}:{node_id}"
        
        for idx, event in enumerate(self.all_events):
            if event.node_id == qualified_node_id:
                return idx
        
        raise ValueError(
            f"Event not found: session={session_id}, node={node_id}. "
            f"This indicates a bug in the graph traversal logic."
        )

# Made with Bob

    
    def _on_node_completed(self, qualified_node_id: str, completion_time: float) -> None:
        """Called when a node completes. Records completion in shared state.

        This is called from worker processes, so we only update the shared
        completion tracker (_shared_node_completions). The main process will
        check this tracker and manage session activation/completion.
        """
        logger.debug(f"_on_node_completed called for {qualified_node_id}")

        # Record completion in shared dict (visible across all processes)
        self._shared_node_completions[qualified_node_id] = completion_time

    def cleanup_session(self, session_id: str) -> None:
        """Clean up memory for a completed session.
        
        Removes all node outputs, messages, and completion tracking data
        for the specified session to prevent memory leaks in long-running
        benchmarks with many sessions.
        
        Args:
            session_id: The session ID to clean up
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to cleanup unknown session: {session_id}")
            return
        
        # Count nodes for logging
        node_count = len(state.graph.nodes)
        
        # Remove node outputs and messages from registry
        for node_id in state.graph.nodes.keys():
            qualified_node_id = f"{session_id}:{node_id}"
            
            # Remove from output registry
            self.output_registry._node_output_text.pop(qualified_node_id, None)
            self.output_registry._node_input_messages.pop(qualified_node_id, None)
            
            # Remove from shared completion tracker. we might use this to track the completion of the session when generating reports, do not pop yet
            # self._shared_node_completions.pop(qualified_node_id, None)
        
        # Remove session state
        del self.session_graph_state[session_id]
        
        logger.debug(
            f"Cleaned up session {session_id}: removed {node_count} nodes from memory"
        )
        logger.debug(f"Recorded completion for {qualified_node_id} in shared tracker")
