# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `NodeOutputRegistry`, which maps
node_id → actual output text. The registry is backed by a `multiprocessing.Manager().dict()`
so it is shared across all worker processes.

The actual output is captured in `OTelChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.
"""

import json
import logging
import multiprocessing as mp
import time
from dataclasses import dataclass, field, replace as dc_replace
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import Any, Dict, Generator, List, Optional

from aiohttp import ClientResponse

from inference_perf.apis import ChatCompletionAPIData, InferenceAPIData, InferenceInfo, LazyLoadInferenceAPIData
from inference_perf.apis.chat import ChatMessage
from inference_perf.config import APIConfig, APIType, DataConfig
from inference_perf.datagen.base import DataGenerator, LazyLoadDataMixin
from inference_perf.datagen.otel_trace_to_replay_graph import (
    GraphCall,
    GraphNode,
    InputSegment,
    ReplayGraph,
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# OTelInferenceInfo — InferenceInfo subclass that carries the output text
# ---------------------------------------------------------------------------

class OTelInferenceInfo(InferenceInfo):
    """InferenceInfo subclass that also carries the raw output text.

    Inherits all fields from InferenceInfo (input_tokens, output_tokens, etc.)
    and adds output_text so the OTel replay path can register the actual
    generated text in the NodeOutputRegistry without touching the base class.
    """
    output_text: Optional[str] = None


# ---------------------------------------------------------------------------
# NodeOutputRegistry — shared cross-process output store
# ---------------------------------------------------------------------------

class NodeOutputRegistry:
    """Thread- and process-safe registry mapping node_id → actual output text.

    Backed by a multiprocessing.Manager().dict() so all worker processes share
    the same store. The manager must be started before the workers are forked.

    Usage:
        manager = mp.Manager()
        registry = NodeOutputRegistry(manager)
        # pass registry to OTelTraceReplayDataGenerator
        # workers call registry.record(node_id, text) after each LLM call
        # load_lazy_data calls registry.require(node_id) to get the output
    """

    def __init__(self, manager: Optional[SyncManager] = None) -> None:
        if manager is not None:
            # Shared across processes via manager proxy
            self._store: Dict[str, str] = manager.dict()  # type: ignore[assignment]
        else:
            # Single-process fallback (e.g., tests, num_workers=0)
            self._store = {}

    def record(self, node_id: str, output_text: str) -> None:
        """Register the actual output text for a completed node."""
        self._store[node_id] = output_text

    def get(self, node_id: str) -> Optional[str]:
        """Return the output text for node_id, or None if not yet registered."""
        return self._store.get(node_id)

    def require(self, node_id: str, timeout_sec: float = 30.0) -> str:
        """Return the output text for node_id, waiting if not yet registered.

        This is called when building the messages for a call that has an "output"
        segment sourced from node_id. If the predecessor has not yet completed,
        this method polls the registry until the output becomes available or timeout.

        Args:
            node_id: The node ID whose output is required
            timeout_sec: Maximum time to wait for the output (default: 30s)

        Returns:
            The output text from the predecessor node

        Raises:
            TimeoutError: If the output is not available within timeout_sec
        """
        start_time = time.time()
        poll_interval = 0.01  # 10ms initial poll interval
        max_poll_interval = 0.5  # Max 500ms between polls
        last_log_time = start_time

        while True:
            output = self._store.get(node_id)
            if output is not None:
                elapsed = time.time() - start_time
                if elapsed > 0.1:  # Log if we had to wait
                    logger.info(f"Got output for node {node_id} after {elapsed:.2f}s wait")
                return output

            elapsed = time.time() - start_time
            
            # Log every 5 seconds while waiting
            if elapsed - (last_log_time - start_time) >= 5.0:
                logger.warning(
                    f"Still waiting for output from node '{node_id}' ({elapsed:.1f}s elapsed)"
                )
                last_log_time = time.time()
            
            if elapsed >= timeout_sec:
                raise TimeoutError(
                    f"NodeOutputRegistry: output for node '{node_id}' not available after "
                    f"{timeout_sec:.1f}s. This means the predecessor call has not completed "
                    f"within the timeout period. Check that predecessor_node_ids are correct "
                    f"and that the predecessor is not blocked or failed."
                )

            # Exponential backoff for polling
            time.sleep(min(poll_interval, max_poll_interval))
            poll_interval *= 1.5

    def wait_for_all(self, node_ids: List[str], timeout_sec: float = 30.0) -> None:
        """Wait for all specified nodes to have registered outputs.

        Args:
            node_ids: List of node IDs to wait for
            timeout_sec: Maximum time to wait for all outputs (default: 30s)

        Raises:
            TimeoutError: If any output is not available within timeout_sec
        """
        if not node_ids:
            return
        
        logger.debug(f"Waiting for {len(node_ids)} predecessor(s): {node_ids}")
        for node_id in node_ids:
            self.require(node_id, timeout_sec=timeout_sec)
        logger.debug(f"All {len(node_ids)} predecessor(s) completed")


# ---------------------------------------------------------------------------
# OTelChatCompletionAPIData — captures output and registers it in the registry
# ---------------------------------------------------------------------------

class OTelChatCompletionAPIData(ChatCompletionAPIData):
    """ChatCompletionAPIData subclass for OTel trace replay.

    Overrides process_response to:
    1. Extract the actual output text from the LLM response.
    2. Register it in the NodeOutputRegistry under this call's node_id.
    3. Return OTelInferenceInfo (InferenceInfo subclass) with output_text populated.

    The registry and node_id are passed at construction time via Pydantic fields.
    arbitrary_types_allowed is required because NodeOutputRegistry is not a Pydantic model.
    
    Dependency handling:
    - predecessor_node_ids: List of nodes that must complete before this one
    - wait_ms: Additional delay after predecessors complete
    - input_segments: Segment decomposition for output substitution
    - original_messages: Original messages before substitution (used as template)
    """

    model_config = {"arbitrary_types_allowed": True}

    node_id: str
    registry: NodeOutputRegistry
    
    # Dependency information for async waiting
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0
    input_segments: List[InputSegment] = field(default_factory=list)
    original_messages: List[Dict[str, Any]] = field(default_factory=list)
    async def wait_for_predecessors_and_substitute(self) -> None:
        """Wait for predecessors asynchronously and substitute output segments.
        
        This method is called by the worker before dispatching the HTTP request.
        It ensures that all predecessor nodes have completed and their outputs
        are available, then substitutes "output" segments with actual predecessor
        outputs instead of the recorded assistant messages.
        
        The waiting is done in an executor to avoid blocking the event loop.
        """
        import asyncio
        
        if self.predecessor_node_ids:
            logger.debug(
                f"Node {self.node_id} waiting for {len(self.predecessor_node_ids)} predecessor(s): "
                f"{self.predecessor_node_ids}"
            )
            # Run blocking wait in executor to avoid blocking event loop
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                self.registry.wait_for_all,
                self.predecessor_node_ids,
                300.0  # 5 minute timeout
            )
            logger.debug(f"Node {self.node_id} predecessors completed")
        
        # Wait additional delay specified in wait_ms
        if self.wait_ms > 0:
            wait_sec = self.wait_ms / 1000.0
            logger.debug(f"Node {self.node_id} waiting {wait_sec:.3f}s (wait_ms={self.wait_ms})")
            await asyncio.sleep(wait_sec)
        
        # Substitute output segments with actual predecessor outputs
        if any(seg.type == "output" for seg in self.input_segments):
            logger.debug(f"Node {self.node_id} substituting output segments")
            substituted = self._build_messages_with_substitution()
            # Update messages with substituted content
            self.messages = [
                ChatMessage(role=m["role"], content=m["content"])
                for m in substituted
            ]
            logger.debug(f"Node {self.node_id} substitution complete, {len(self.messages)} messages")
    
    def _build_messages_with_substitution(self) -> List[Dict[str, Any]]:
        """Build messages with output segments substituted with actual predecessor outputs.
        
        Returns:
            List of message dicts with "output" segments replaced by actual LLM outputs
        """
        if not self.input_segments:
            return self.original_messages
        
        result = []
        cursor = 0
        
        for seg in self.input_segments:
            # Get the messages for this segment
            seg_msgs = self.original_messages[cursor:cursor + seg.message_count]
            
            if seg.type in ("shared", "unique"):
                # Keep these messages as-is
                result.extend(seg_msgs)
            elif seg.type == "output":
                # Substitute with actual output from predecessor
                if seg.source_node_id is None:
                    logger.warning(
                        f"Node {self.node_id}: output segment has no source_node_id, "
                        f"using recorded content"
                    )
                    result.extend(seg_msgs)
                    cursor += seg.message_count
                    continue
                
                actual_output = self.registry.get(seg.source_node_id)
                if actual_output is None:
                    # Fallback to original if not available (shouldn't happen after wait)
                    logger.warning(
                        f"Node {self.node_id}: output segment from {seg.source_node_id} "
                        f"not available, using recorded content"
                    )
                    result.extend(seg_msgs)
                else:
                    # Replace each message in this segment with the actual output
                    for msg in seg_msgs:
                        substituted = dict(msg)
                        substituted["content"] = actual_output
                        result.append(substituted)
                    logger.debug(
                        f"Node {self.node_id}: substituted {seg.message_count} message(s) "
                        f"from {seg.source_node_id} with {len(actual_output)} chars"
                    )
            else:
                # Unknown segment type, keep as-is
                result.extend(seg_msgs)
            
            cursor += seg.message_count
        
        return result
    
    def register_mock_completion(self, output_text: str = "") -> None:
        """Register a completion for mock/test scenarios.
        
        This should be called after a mock request completes to unblock
        dependent nodes that are waiting for this node's output.
        
        Args:
            output_text: The output text to register (empty string for mock)
        """
        self.registry.record(self.node_id, output_text)
        logger.debug(f"Registered mock completion for node {self.node_id}")


    async def process_response(
        self,
        response: ClientResponse,
        config: APIConfig,
        tokenizer: CustomTokenizer,
        lora_adapter: Optional[str] = None,
    ) -> OTelInferenceInfo:
        """Process the LLM response, capture output text, and register it."""
        output_text: str = ""

        if config.streaming:
            output_text = ""
            output_token_times: List[float] = []
            buffer = b""
            async for chunk in response.content.iter_any():
                buffer += chunk
                while b"\n\n" in buffer:
                    message, buffer = buffer.split(b"\n\n", 1)
                    output_token_times.append(time.perf_counter())
                    for line in message.split(sep=b"\n"):
                        if line.startswith(b"data:"):
                            data_str = line.removeprefix(b"data: ").strip()
                            if data_str == b"[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                choices = data.get("choices", [])
                                if choices:
                                    delta = choices[0].get("delta", {})
                                    content = delta.get("content")
                                    if content:
                                        output_text += content
                            except (json.JSONDecodeError, IndexError):
                                continue
                    else:
                        continue
                    break

            prompt_text = "".join([msg.content for msg in self.messages if msg.content])
            prompt_len = tokenizer.count_tokens(prompt_text)
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                output_token_times=output_token_times,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )
        else:
            data = await response.json()
            prompt_len = tokenizer.count_tokens("".join([m.content for m in self.messages]))
            choices = data.get("choices", [])
            if choices:
                output_text = "".join(
                    [choice.get("message", {}).get("content", "") for choice in choices]
                )
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )

        # Register the actual output in the shared registry so downstream calls
        # (those with "output" segments sourced from this node) can substitute it.
        # Always register something (even empty string) so dependent nodes don't wait forever.
        output_to_register = output_text or ""
        self.registry.record(self.node_id, output_to_register)
        if output_text:
            logger.debug(
                f"Registered output for node {self.node_id}: {len(output_text)} chars"
            )
        else:
            logger.debug(f"Registered empty output for node {self.node_id}")

        return info


# ---------------------------------------------------------------------------
# OTelTraceReplayEvent — one event per graph node
# ---------------------------------------------------------------------------

@dataclass
class OTelTraceReplayEvent:
    """Represents a single LLM request event from an OTel trace, derived from a GraphCall."""

    call_id: str
    node_id: str
    file_index: int
    t_start_ms: int   # node start time (adjusted for time_scale + session offset)
    t_end_ms: int     # node end time
    model: str
    messages: List[Dict[str, Any]]          # original (recorded) messages — used as template
    input_segments: List[InputSegment]      # segment decomposition for output substitution
    expected_output_tokens: int
    temperature: Optional[float]
    max_tokens_recorded: Optional[int]
    # Predecessor node IDs (nodes that must complete before this one starts)
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0


@dataclass
class OTelTraceSession:
    """Represents a complete session (one OTel file) as a ReplayGraph."""

    session_id: str
    file_path: Path
    file_index: int
    graph: ReplayGraph
    start_offset_ms: int = 0  # Offset for staggered session starts


class OTelTraceReplayDataGenerator(DataGenerator, LazyLoadDataMixin):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.
    
    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """
    
    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
    ) -> None:
        super().__init__(api_config, config, tokenizer)
        
        if not hasattr(config, 'otel_trace_replay') or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")
        
        self.otel_config = config.otel_trace_replay
        
        # Determine if we're loading from a directory or a single file
        if self.otel_config.trace_directory:
            self.trace_dir = Path(self.otel_config.trace_directory)
            self.single_file_mode = False
            
            if not self.trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {self.trace_dir}")
            
            if not self.trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {self.trace_dir}")
        elif self.otel_config.trace_file:
            # Single file mode
            self.trace_file = Path(self.otel_config.trace_file)
            self.single_file_mode = True
            
            if not self.trace_file.exists():
                raise ValueError(f"Trace file does not exist: {self.trace_file}")
            
            if not self.trace_file.is_file():
                raise ValueError(f"Trace file path is not a file: {self.trace_file}")
            
            if not self.trace_file.suffix == '.json':
                raise ValueError(f"Trace file must be a JSON file: {self.trace_file}")
            
            # Set trace_dir to parent directory for consistency
            self.trace_dir = self.trace_file.parent
        else:
            raise ValueError("Either trace_directory or trace_file must be provided in otel_trace_replay config")

        # Output registry: shared across all worker processes via mp.Manager().dict()
        # If mp_manager is None (single-process mode), falls back to a plain dict.
        self.output_registry = NodeOutputRegistry(manager=mp_manager)
        
        # Load and process all OTel trace files
        self.sessions: List[OTelTraceSession] = []
        self._load_trace_files()
        
        if not self.sessions:
            raise ValueError(f"No valid OTel trace files found in {self.trace_dir}")
        
        # Build flat list of all events across all sessions for replay
        self._build_replay_schedule()
        
        logger.info(
            f"Loaded {len(self.sessions)} sessions with {len(self.all_events)} total events "
            f"from {self.trace_dir}"
        )
    
    def _load_trace_files(self) -> None:
        """Load and process OTel JSON files from either a directory or a single file."""
        if self.single_file_mode:
            # Single file mode: load only the specified file
            logger.info(f"Loading single trace file: {self.trace_file}")
            try:
                session = self._process_trace_file(self.trace_file, 0)
                if session:
                    self.sessions.append(session)
                    node_count = len(session.graph.nodes)
                    logger.info(
                        f"Loaded session {session.session_id} from {self.trace_file.name} "
                        f"with {node_count} nodes"
                    )
                else:
                    logger.warning(f"No valid session found in {self.trace_file}")
            except Exception as e:
                logger.error(f"Failed to process trace file {self.trace_file}: {e}")
                raise
        else:
            # Directory mode: load all JSON files from the directory
            trace_files = sorted(self.trace_dir.glob("*.json"))
            
            if not trace_files:
                logger.warning(f"No JSON files found in {self.trace_dir}")
                return
            
            logger.info(f"Found {len(trace_files)} trace files in {self.trace_dir}")
            
            for file_index, trace_file in enumerate(trace_files):
                try:
                    session = self._process_trace_file(trace_file, file_index)
                    if session:
                        self.sessions.append(session)
                        node_count = len(session.graph.nodes)
                        logger.info(
                            f"Loaded session {session.session_id} from {trace_file.name} "
                            f"with {node_count} nodes"
                        )
                except Exception as e:
                    logger.error(f"Failed to process trace file {trace_file}: {e}")
                    if not self.otel_config.skip_invalid_files:
                        raise
    
    def _process_trace_file(self, trace_file: Path, file_index: int) -> Optional[OTelTraceSession]:
        """Process a single OTel JSON trace file into a ReplayGraph session."""
        try:
            data = json.loads(trace_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {trace_file}: {e}")
            return None

        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {trace_file}")
            return None

        raw_calls = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
        if not raw_calls:
            logger.warning(f"No LLM calls found in {trace_file}")
            return None

        graph = build_graph(
            raw_calls,
            source_file=str(trace_file),
        )

        # Use trace_id from first call as session_id
        session_id = raw_calls[0].trace_id or str(file_index)

        return OTelTraceSession(
            session_id=session_id,
            file_path=trace_file,
            file_index=file_index,
            graph=graph,
        )
    
    def _build_replay_schedule(self) -> None:
        """Build the replay schedule with staggered session starts.

        Flattens all graph nodes across all sessions into a list of
        OTelTraceReplayEvents sorted by adjusted start time.
        """
        self.all_events: List[OTelTraceReplayEvent] = []

        session_delay_ms = int(self.otel_config.session_start_delay_sec * 1000)
        concurrent_sessions = self.otel_config.concurrent_sessions

        for i, session in enumerate(self.sessions):
            if concurrent_sessions > 0:
                batch_index = i // concurrent_sessions
                session.start_offset_ms = batch_index * session_delay_ms
            else:
                session.start_offset_ms = i * session_delay_ms

            # Flatten graph nodes → replay events (one node = one call)
            for node in session.graph.nodes.values():
                t_start = int(node.t_start_ms * self.otel_config.time_scale) + session.start_offset_ms
                t_end = int(node.t_end_ms * self.otel_config.time_scale) + session.start_offset_ms
                gc = node.call

                if not gc.messages:
                    logger.warning(f"Call {gc.call_id} in node {node.node_id} has no messages, skipping")
                    continue

                # Qualify node_id with session to avoid collisions across sessions
                qualified_node_id = f"{session.session_id}:{node.node_id}"
                qualified_predecessor_ids = [
                    f"{session.session_id}:{pid}" for pid in node.predecessor_node_ids
                ]

                # Rewrite source_node_id in input_segments to use qualified node IDs,
                # so the registry lookup in load_lazy_data uses the same key space.
                qualified_segments = [
                    dc_replace(seg, source_node_id=f"{session.session_id}:{seg.source_node_id}")
                    if seg.source_node_id is not None
                    else seg
                    for seg in gc.input_segments
                ]

                self.all_events.append(OTelTraceReplayEvent(
                    call_id=gc.call_id,
                    node_id=qualified_node_id,
                    file_index=session.file_index,
                    t_start_ms=t_start,
                    t_end_ms=t_end,
                    model=gc.model,
                    messages=gc.messages,
                    input_segments=qualified_segments,
                    expected_output_tokens=gc.expected_output_tokens,
                    temperature=gc.temperature,
                    max_tokens_recorded=gc.max_tokens_recorded,
                    predecessor_node_ids=qualified_predecessor_ids,
                    wait_ms=node.wait_ms,
                ))

        self.all_events.sort(key=lambda e: e.t_start_ms)

        logger.info(
            f"Built replay schedule: {len(self.all_events)} events across "
            f"{len(self.sessions)} sessions, time_scale={self.otel_config.time_scale}"
        )
    
    def _get_effective_model(self, recorded_model: str) -> str:
        """Get the effective model name for a request."""
        if self.otel_config.use_static_model:
            # Use static model from config
            return self.otel_config.static_model_name
        else:
            # Use model mapping if provided
            if self.otel_config.model_mapping:
                return self.otel_config.model_mapping.get(recorded_model, recorded_model)
            return recorded_model
    
    def _build_messages_with_substitution(
        self,
        event: OTelTraceReplayEvent,
    ) -> List[Dict[str, Any]]:
        """Build the message list for a call, substituting "output" segments with
        actual outputs from the NodeOutputRegistry.

        Algorithm:
        - Walk through input_segments in order, tracking a cursor over event.messages.
        - For "shared" and "unique" segments: copy messages as-is (cursor advances by message_count).
        - For "output" segments: replace the assistant message content with the actual
          output from the registry (keyed by segment.source_node_id).

        Raises:
            KeyError: if a required predecessor output is not yet in the registry.
                      This indicates a dependency ordering violation.
                      Alternative (not implemented): fall back to the recorded static text
                      by catching KeyError and using event.messages[cursor]["content"] instead.
        """
        if not event.input_segments:
            # No segment info — use messages as-is (no substitution possible)
            return list(event.messages)

        result: List[Dict[str, Any]] = []
        cursor = 0

        for seg in event.input_segments:
            seg_msgs = event.messages[cursor: cursor + seg.message_count]

            if seg.type in ("shared", "unique"):
                # Keep messages verbatim
                result.extend(seg_msgs)

            elif seg.type == "output":
                # Substitute with actual output from the registry
                assert seg.source_node_id is not None, (
                    f"Output segment for call {event.call_id} has no source_node_id"
                )
                actual_output = self.output_registry.require(seg.source_node_id)

                # Replace each message in this segment (always 1 for "output" segments)
                for msg in seg_msgs:
                    substituted = dict(msg)
                    substituted["content"] = actual_output
                    result.append(substituted)

            else:
                # Unknown segment type — pass through unchanged
                logger.warning(
                    f"Unknown segment type '{seg.type}' for call {event.call_id}, passing through"
                )
                result.extend(seg_msgs)

            cursor += seg.message_count

        # Append any remaining messages not covered by segments (safety net)
        if cursor < len(event.messages):
            result.extend(event.messages[cursor:])

        return result

    def get_request_count(self) -> int:
        """Return total number of requests to replay."""
        return len(self.all_events)
    
    def get_supported_apis(self) -> List[APIType]:
        """Return supported API types."""
        return [APIType.Chat]
    
    def is_io_distribution_supported(self) -> bool:
        """IO distribution not supported for trace replay."""
        return False
    
    def is_shared_prefix_supported(self) -> bool:
        """Shared prefix not supported for trace replay."""
        return False
    
    def get_session_count(self) -> int:
        """Return the total number of sessions (trace files) available for replay."""
        return len(self.sessions)
    
    def get_session_event_indices(self, session_index: int) -> List[int]:
        """Get the event indices for a specific session.
        
        Args:
            session_index: Index of the session (0-based)
            
        Returns:
            List of event indices (into self.all_events) that belong to this session
            
        Raises:
            IndexError: If session_index is out of range
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")
        
        session = self.sessions[session_index]
        # Find all events that belong to this session by matching file_index
        return [i for i, event in enumerate(self.all_events) if event.file_index == session.file_index]
    
    def get_session_info(self, session_index: int) -> Dict[str, Any]:
        """Get information about a specific session.
        
        Args:
            session_index: Index of the session (0-based)
            
        Returns:
            Dictionary with session metadata
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")
        
        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)
        
        return {
            "session_id": session.session_id,
            "file_path": str(session.file_path),
            "file_index": session.file_index,
            "num_events": len(event_indices),
            "num_nodes": len(session.graph.nodes),
            "start_offset_ms": session.start_offset_ms,
        }

        return False
    
    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        """Load the actual request data for a given index.

        This method NO LONGER blocks waiting for predecessors. Instead, it passes
        the dependency information (predecessor_node_ids, wait_ms, input_segments)
        to the OTelChatCompletionAPIData instance, which will handle async waiting
        in the worker before dispatching the HTTP request.

        This prevents deadlock: workers don't block synchronously, so they can
        process multiple requests and complete predecessors while others wait.

        Returns an OTelChatCompletionAPIData instance that will:
        1. Wait for predecessors asynchronously (in worker)
        2. Substitute output segments with actual predecessor outputs
        3. Register its own output after the LLM call completes
        """
        n = data.data_index

        if n >= len(self.all_events):
            raise IndexError(f"Event index {n} out of range (total: {len(self.all_events)})")

        event = self.all_events[n]

        # Convert messages to ChatMessage objects (no substitution yet - that happens async)
        chat_messages = []
        for msg in event.messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")

            # Handle content that might be a list (tool blocks)
            if isinstance(content, list):
                content_parts = []
                for block in content:
                    if isinstance(block, dict):
                        if block.get("type") == "text":
                            content_parts.append(block.get("text", ""))
                        else:
                            content_parts.append(json.dumps(block))
                    else:
                        content_parts.append(str(block))
                content = " ".join(content_parts)

            chat_messages.append(ChatMessage(role=role, content=str(content)))

        # Use expected_output_tokens (from trace) so downstream prefix matching works.
        # Fall back to config default if not available.
        max_tokens = event.expected_output_tokens or self.otel_config.default_max_tokens

        # Return OTelChatCompletionAPIData with dependency info
        # The worker will call wait_for_predecessors_and_substitute() before dispatching
        return OTelChatCompletionAPIData(
            messages=chat_messages,
            max_tokens=max_tokens,
            node_id=event.node_id,
            registry=self.output_registry,
            # Pass dependency info for async handling
            predecessor_node_ids=event.predecessor_node_ids,
            wait_ms=event.wait_ms,
            input_segments=event.input_segments,
            original_messages=event.messages,
        )
    
    def get_data(self) -> Generator[InferenceAPIData, None, None]:
        """Generate lazy-load data objects for all events.
        
        Cycles through events repeatedly to support load generation that
        may request more items than available in the trace.
        """
        if self.api_config.type != APIType.Chat:
            raise Exception(
                f"Unsupported API type: {self.api_config.type}. "
                "OTelTraceReplayDataGenerator only supports Chat API."
            )
        
        if not self.all_events:
            raise Exception("No events available for replay")
        
        # Cycle through events indefinitely
        i = 0
        while True:
            yield LazyLoadInferenceAPIData(data_index=i % len(self.all_events))
            i += 1

# Made with Bob
